import Pinwheel

#print axioms Pinwheel.Binary.fin_law
#print axioms Pinwheel.Binary.bool_law
#print axioms Pinwheel.Binary.bits_law
#print axioms Pinwheel.Binary.option_law
#print axioms Pinwheel.Binary.from_to_bytes
#print axioms Pinwheel.Binary.to_from_bytes
#print axioms Pinwheel.Binary.decode_encode_bytes
#print axioms Pinwheel.Binary.list_law
#print axioms Pinwheel.Binary.vector_law
#print axioms Pinwheel.Binary.execute_encode
#print axioms Pinwheel.Binary.load_encode
#print axioms Pinwheel.Binary.load_reject
#print axioms Pinwheel.Binary.counted_i2c_eq
#print axioms Pinwheel.Binary.explicit_agrees
#print axioms Pinwheel.Binary.execute_explicit
#print axioms Pinwheel.Binary.binary_i2c_eq
#print axioms Pinwheel.Binary.literal_finish_eval
#print axioms Pinwheel.Binary.literal_sample_eval
#print axioms Pinwheel.Binary.literal_eval
#print axioms Pinwheel.Binary.instruction_law
#print axioms Pinwheel.Binary.expect_law
#print axioms Pinwheel.Binary.image_law
#print axioms Pinwheel.Binary.decode_encode
#print axioms Pinwheel.Binary.encode_decode
#print axioms Pinwheel.Binary.code_law
#print axioms Pinwheel.Binary.pins_law
#print axioms Pinwheel.Binary.index_law
#print axioms Pinwheel.Binary.serial_law
#print axioms Pinwheel.Binary.pin_expr_law
#print axioms Pinwheel.Binary.sample_law
#print axioms Pinwheel.Binary.condition_law
#print axioms Pinwheel.Binary.check_law
#print axioms Pinwheel.Binary.target_law
#print axioms Pinwheel.Binary.transfer_law
#print axioms Pinwheel.Binary.successor_law
#print axioms Pinwheel.Binary.sample_option_law
#print axioms Pinwheel.Binary.template_law
