import Pinwheel.Hardware.Loader.Contract

#print axioms Pinwheel.Hardware.Loader.Machine.active_memory_preserved
#print axioms Pinwheel.Hardware.Loader.Machine.interrupted_upload_preserves_program
#print axioms Pinwheel.Hardware.Loader.Machine.commit_does_not_write
#print axioms Pinwheel.Hardware.Loader.Machine.commit_switches_image
#print axioms Pinwheel.Hardware.Loader.Machine.commit_resets_execution
#print axioms Pinwheel.Hardware.Loader.Machine.initialize_safe
#print axioms Pinwheel.Hardware.Loader.Machine.uncommitted_safe
#print axioms Pinwheel.Hardware.Loader.Machine.prefix_push
#print axioms Pinwheel.Hardware.Loader.Machine.valid_push
#print axioms Pinwheel.Hardware.Loader.Machine.valid_commit
#print axioms Pinwheel.Hardware.Loader.Machine.valid_next
#print axioms Pinwheel.Hardware.Loader.Machine.initialize_valid
#print axioms Pinwheel.Hardware.Loader.Machine.valid_run
#print axioms Pinwheel.Hardware.Loader.Machine.control_correct
#print axioms Pinwheel.Hardware.Loader.Machine.commit_correct
#print axioms Pinwheel.Hardware.Loader.Machine.selected_correct
#print axioms Pinwheel.Hardware.Loader.Machine.chosen_correct
#print axioms Pinwheel.Hardware.Loader.Machine.read_correct
#print axioms Pinwheel.Hardware.Loader.Machine.usable_correct
#print axioms Pinwheel.Hardware.Loader.Machine.base_correct
#print axioms Pinwheel.Hardware.Loader.Machine.scheduler_correct
#print axioms Pinwheel.Hardware.Loader.Machine.memory_correct
#print axioms Pinwheel.Hardware.Loader.Machine.next_correct
#print axioms Pinwheel.Hardware.Loader.Machine.run_correct
#print axioms Pinwheel.Hardware.Loader.gate_correct
#print axioms Pinwheel.Hardware.Loader.word_correct
#print axioms Pinwheel.Hardware.Loader.push_correct
#print axioms Pinwheel.Hardware.Loader.commit_correct
#print axioms Pinwheel.Hardware.Loader.start_correct
#print axioms Pinwheel.Hardware.Loader.rejected_correct
#print axioms Pinwheel.Hardware.Loader.next_correct
#print axioms Pinwheel.Hardware.Loader.commit_requires_complete
#print axioms Pinwheel.Hardware.Loader.commit_next
#print axioms Pinwheel.Hardware.Loader.push_requires_valid
#print axioms Pinwheel.Hardware.Loader.push_next
#print axioms Pinwheel.Hardware.Loader.no_commit_preserves_selection
#print axioms Pinwheel.Hardware.Loader.cursor_increment
#print axioms Pinwheel.Hardware.Loader.cursor_bounded
#print axioms Pinwheel.Hardware.Loader.Store.width_bound
#print axioms Pinwheel.Hardware.Loader.Store.next_correct
#print axioms Pinwheel.Hardware.Loader.Store.read_correct
