import Pinwheel.Hardware.Reactive.CoreProofs

#print axioms Pinwheel.Hardware.Reactive.Core.address_correct
#print axioms Pinwheel.Hardware.Reactive.Core.base_correct
#print axioms Pinwheel.Hardware.Reactive.Core.blocked_correct
#print axioms Pinwheel.Hardware.Reactive.Core.busy_correct
#print axioms Pinwheel.Hardware.Reactive.Core.core_next
#print axioms Pinwheel.Hardware.Reactive.Core.direct_represents
#print axioms Pinwheel.Hardware.Reactive.Core.direct_run
#print axioms Pinwheel.Hardware.Reactive.Core.direct_stable
#print axioms Pinwheel.Hardware.Reactive.Core.indexed_represents
#print axioms Pinwheel.Hardware.Reactive.Core.indexed_run
#print axioms Pinwheel.Hardware.Reactive.Core.indexed_stable
#print axioms Pinwheel.Hardware.Reactive.Core.inputs_correct
#print axioms Pinwheel.Hardware.Reactive.Core.machine_next
#print axioms Pinwheel.Hardware.Reactive.Core.machine_run
#print axioms Pinwheel.Hardware.Reactive.Core.memory_write_hold
#print axioms Pinwheel.Hardware.Reactive.Core.metadata_hold
#print axioms Pinwheel.Hardware.Reactive.advance_active
#print axioms Pinwheel.Hardware.Reactive.advance_checked
#print axioms Pinwheel.Hardware.Reactive.advance_correct
#print axioms Pinwheel.Hardware.Reactive.advance_qualifying
#print axioms Pinwheel.Hardware.Reactive.advance_waiting
#print axioms Pinwheel.Hardware.Reactive.captureSlots_correct
#print axioms Pinwheel.Hardware.Reactive.current_correct
#print axioms Pinwheel.Hardware.Reactive.decrement_correct
#print axioms Pinwheel.Hardware.Reactive.dispatch_checked
#print axioms Pinwheel.Hardware.Reactive.dispatch_correct
#print axioms Pinwheel.Hardware.Reactive.dispatch_sequential
#print axioms Pinwheel.Hardware.Reactive.enter_encoded
#print axioms Pinwheel.Hardware.Reactive.entrySlots_correct
#print axioms Pinwheel.Hardware.Reactive.entry_correct
#print axioms Pinwheel.Hardware.Reactive.exit_correct
#print axioms Pinwheel.Hardware.Reactive.fed_entry
#print axioms Pinwheel.Hardware.Reactive.from_values
#print axioms Pinwheel.Hardware.Reactive.guard_correct
#print axioms Pinwheel.Hardware.Reactive.inputBit_correct
#print axioms Pinwheel.Hardware.Reactive.kind_correct
#print axioms Pinwheel.Hardware.Reactive.next_correct
#print axioms Pinwheel.Hardware.Reactive.predecessor_counter
#print axioms Pinwheel.Hardware.Reactive.progress_correct
#print axioms Pinwheel.Hardware.Reactive.range_correct
#print axioms Pinwheel.Hardware.Reactive.ready_correct
#print axioms Pinwheel.Hardware.Reactive.retry_correct
#print axioms Pinwheel.Hardware.Reactive.run_refines
#print axioms Pinwheel.Hardware.Reactive.running_correct
#print axioms Pinwheel.Hardware.Reactive.running_embed
#print axioms Pinwheel.Hardware.Reactive.sequential_correct
#print axioms Pinwheel.Hardware.Reactive.step_refines
#print axioms Pinwheel.Hardware.Reactive.stop_correct
#print axioms Pinwheel.Hardware.Reactive.successor_address
#print axioms Pinwheel.Hardware.Reactive.successor_correct
#print axioms Pinwheel.Hardware.Reactive.target_correct
#print axioms Pinwheel.Hardware.Reactive.terminal_correct
#print axioms Pinwheel.Hardware.Reactive.tick_correct
#print axioms Pinwheel.Hardware.Reactive.tick_refines
#print axioms Pinwheel.Hardware.Reactive.view_embed
