name = "pinwheel"
version = "0.1.0"
defaultTargets = ["Pinwheel"]

[leanOptions]
warningAsError = true

[[lean_lib]]
name = "Pinwheel"

[[lean_exe]]
name = "backend_emit"
root = "test.Backend"

[[lean_exe]]
name = "bank_select_emit"
root = "test.BankSelect"

[[lean_exe]]
name = "sampled_emit"
root = "test.Sampled"
