import Pinwheel.Compile.Readiness
import Pinwheel.Hardware.Storage.SramSchedule
import Pinwheel.Hardware.Storage.UploadPipeline
import Pinwheel.Hardware.NetlistInputs
import Pinwheel.Hardware.Storage.AdmissionNetlist
import Pinwheel.Hardware.Loader.Contract
import Std
import Pinwheel.Binary.Execution
import Pinwheel.Binary.Bytes
import Pinwheel.Binary.Storage
import Pinwheel.I2C.Proofs
import Pinwheel.Engine.Compatibility
import Pinwheel.Engine.ControlProofs
import Pinwheel.Compile.StretchedPulse
import Pinwheel.Compile.I2CReadProofs
import Pinwheel.I2C.RegisterReadTransactionProofs
import Pinwheel.Compile.I2CReadTransactionProofs
import Pinwheel.Compile.I2CWriteTransactionProofs
import Pinwheel.Compile.I2CRecoveryProofs
import Pinwheel.Compile.I2CProofs
import Pinwheel.Compile.I2CLoopCorrectness
import Pinwheel.UART.Tx
import Pinwheel.SPI.Controller
import Pinwheel.Compile.UART
import Pinwheel.Compile.UARTLink
import Pinwheel.Compile.UARTRxStream
import Pinwheel.Compile.UARTStreamLink
import Pinwheel.UART.LinkPipeline
import Pinwheel.Compile.SPI
import Pinwheel.Compile.SPITransaction
import Pinwheel.Hardware.RawProgram
import Pinwheel.Hardware.Countdown
import Pinwheel.Hardware.CountdownContract
import Pinwheel.Hardware.PinBoundary
import Pinwheel.Hardware.Emit
import Pinwheel.Hardware.Execution.Emit
import Pinwheel.Hardware.Reactive.Emit
import Pinwheel.Hardware.Refinement
import Pinwheel.Hardware.Protocols
import Pinwheel.Hardware.Storage
import Pinwheel.Hardware.Storage.BackendEmit
import Pinwheel.Hardware.Storage.BackendReadback
import Pinwheel.Hardware.Storage.BankSelect
import Pinwheel.Hardware.Storage.BankSelectReadback
import Pinwheel.Hardware.Storage.CacheEnable
import Pinwheel.Hardware.Storage.SampledBackend
import Pinwheel.Hardware.Storage.EnabledBackend
import Pinwheel.Hardware.InputLatency
import Pinwheel.Hardware.Memory
import Pinwheel.Hardware.Memory.Flops
import Pinwheel.Hardware.Memory.Registered
import Pinwheel.Hardware.Memory.Sram
import Pinwheel.Hardware.Storage.MemoryView
import Pinwheel.Hardware.Storage.Prefetch
import Pinwheel.Hardware.TimedRule
import Pinwheel.Hardware.Storage.Dispatch
import Pinwheel.Hardware.Storage.ImageRule
import Pinwheel.Hardware.Storage.Admission
import Pinwheel.Hardware.Storage.FetchPolicy
import Pinwheel.Hardware.Storage.Decoupled
import Pinwheel.Hardware.Storage.PolicyBackend
import Pinwheel.Hardware.Storage.PolicyEmit
import Pinwheel.Hardware.Storage.PrefetchBackend
import Pinwheel.Hardware.Storage.PrefetchEmit
import Pinwheel.Hardware.Storage.SinglePort
import Pinwheel.Hardware.Storage.TwoPort
import Pinwheel.Hardware.Storage.Sram
import Pinwheel.Hardware.Storage.OnePortBackend
import Pinwheel.Hardware.Storage.OnePortEmit
import Pinwheel.Hardware.Storage.TwoPortBackend
import Pinwheel.Hardware.Storage.TwoPortEmit
import Pinwheel.Hardware.Storage.DataPort
import Pinwheel.Hardware.Feeder
import Pinwheel.Hardware.Serial.Receiver
import Pinwheel.Hardware.Serial.Frame
import Pinwheel.Hardware.Chip
import Pinwheel.Hardware.Storage.ChipBackend
import Pinwheel.Hardware.Loader.Delivery
import Pinwheel.Hardware.Loader.Upload
import Pinwheel.Hardware.Loader.Program
import Pinwheel.Hardware.Storage.ProgramUpload
import Pinwheel.Hardware.Storage.ChipUpload
import Pinwheel.Hardware.Storage.Readiness
import Pinwheel.SPI.Latency
import Pinwheel.I2C.Latency
import Pinwheel.Compile.SPILatency
import Pinwheel.Hardware.Readback.Boolean
import Pinwheel.Hardware.Reactive.FetchChoice
import Pinwheel.Hardware.UARTRx
import Pinwheel.Hardware.Storage.SramController
import Pinwheel.Hardware.Storage.SramCoverage
import Pinwheel.Hardware.Storage.SramContents
import Pinwheel.Hardware.Storage.SramExecution
import Pinwheel.Hardware.Storage.MapTile
import Pinwheel.Hardware.Storage.TiledController
import Pinwheel.Hardware.Storage.FetchContract
import Pinwheel.Hardware.Storage.PairedController
import Pinwheel.Hardware.Storage.PairedValidation
import Pinwheel.Hardware.Storage.PairedImage
import Pinwheel.Hardware.Storage.PairedResidentImage
import Pinwheel.Hardware.Storage.PairedResidentEffects
import Pinwheel.Hardware.Storage.PairedClosed
import Pinwheel.Hardware.Storage.PairedCoverage
import Pinwheel.Hardware.Storage.PairedRuntime
import Pinwheel.Hardware.Storage.PairedTimed
import Pinwheel.Hardware.Storage.PairedHost
import Pinwheel.Hardware.Storage.PairedSession
import Pinwheel.Hardware.HostResultBuffer
import Pinwheel.UART.BufferedSupervisor
import Pinwheel.Hardware.Storage.PairedStream
import Pinwheel.Hardware.Storage.PairedStreamPackage
import Pinwheel.Hardware.Storage.PairedStreamOwnership
import Pinwheel.Hardware.Storage.PairedStreamBootstrap
import Pinwheel.Hardware.Storage.PairedStreamLifecycle
import Pinwheel.Hardware.Storage.PairedStreamOrigin
import Pinwheel.Hardware.Storage.PairedStreamArm
import Pinwheel.Hardware.Storage.PairedStreamProgram
import Pinwheel.Hardware.Storage.PairedStreamUART
import Pinwheel.UART.BufferedSupervisorPhase
import Pinwheel.Program.Requests
import Pinwheel.Program.ResidentProofs
import Pinwheel.Program.TransferProofs
import Pinwheel.Program.BufferedProofs
import Pinwheel.Program.BufferedI2C
import Pinwheel.Hardware.Buffered.LinearProofs
import Pinwheel.Hardware.Buffered.CountedProofs
import Pinwheel.Hardware.Buffered.ReactiveProofs
import Pinwheel.Hardware.Buffered.SharedBranchProofs
import Pinwheel.Hardware.Buffered.FetchDeadline
import Pinwheel.Hardware.Buffered.SramModel
import Pinwheel.Hardware.Buffered.SramProofs
import Pinwheel.Hardware.Buffered.SerialModel
import Pinwheel.Hardware.Buffered.SerialProofs
import Pinwheel.Hardware.Buffered.SramCorrespondence
import Pinwheel.Hardware.Buffered.SpiSource

/-!
Pinwheel library entry point: protocol models, shared engine, compilers, and proofs.
The small setup example below is retained as a toolchain check.
-/

namespace Pinwheel.Setup

/-- Complement each bit of a byte, for setup validation. -/
def invertByte (byte : BitVec 8) : BitVec 8 := ~~~byte

/-- Complementing a byte twice restores its original value. -/
theorem invertByte_involutive (byte : BitVec 8) : invertByte (invertByte byte) = byte := by
  simp [invertByte]

end Pinwheel.Setup
